<?php

namespace ich\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuditoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriaRepository extends EntityRepository
{
}
