<?php

namespace ich\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CopiaPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopiaPreguntaRepository extends EntityRepository
{
}
