<?php

namespace ich\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuestionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuestionarioRepository extends EntityRepository
{
}
