<?php

namespace ich\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * puesto_competenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class puesto_competenciaRepository extends EntityRepository
{
}
