#ich_test_homepage:
#    path:     /
#    defaults: { _controller: ichTestBundle:Default:index }

# Puesto

ich_puesto_index:
    path:       /puesto/index
    defaults:   { _controller: ichTestBundle:Puesto:index }
    
ich_puesto_add:
    path:       /puesto/add
    defaults:   { _controller: ichTestBundle:Puesto:add }
  
ich_puesto_create:
    path:       /puesto/create
    defaults:   { _controller: ichTestBundle:Puesto:create }
    methods: POST
    
ich_puesto_edit:
    path:       /puesto/edit/{id}
    defaults:   { _controller: ichTestBundle:Puesto:edit }
    
ich_puesto_update:
    path:       /puesto/update/{id}
    defaults:   { _controller: ichTestBundle:Puesto:update }
    methods: [POST, PUT]
    
    
# Pregunta


ich_pregunta_cargarCompetenciaEdit:
    path:       /pregunta/cargarCompetenciaEdit
    defaults:   { _controller: ichTestBundle:Pregunta:cargarCompetenciaEdit }
    methods: POST
    
ich_pregunta_cargarOpcionesEdit:
    path:       /pregunta/cargarOpcionesEdit
    defaults:   { _controller: ichTestBundle:Pregunta:cargarOpcionesEdit }
    methods: POST
    
ich_pregunta_cargarOpciones:
    path:       /pregunta/cargarOpciones
    defaults:   { _controller: ichTestBundle:Pregunta:cargarOpciones }
    methods: POST
    
ich_pregunta_index:
    path:       /pregunta/index
    defaults:   { _controller: ichTestBundle:Pregunta:index }
    
ich_pregunta_add:
    path:       /pregunta/add
    defaults:   { _controller: ichTestBundle:Pregunta:add }

ich_pregunta_create:
    path:       /pregunta/create
    defaults:   { _controller: ichTestBundle:Pregunta:create }
    methods: POST
    
ich_pregunta_edit:
    path:       /pregunta/edit/{id}
    defaults:   { _controller: ichTestBundle:Pregunta:edit }
    
ich_pregunta_update:
    path:       /pregunta/update/{id}
    defaults:   { _controller: ichTestBundle:Pregunta:update }
    methods: [POST, PUT]

ich_pregunta_delete:
    path: /pregunta/delete/{id}
    defaults: { _controller: ichTestBundle:Pregunta:delete }
    methods: [POST,DELETE]
    


# Evaluacion
ich_evaluacion_newStep1:
    path:       /evaluacion/new
    defaults:   { _controller: ichTestBundle:Evaluacion:newStep1 }
    
ich_evaluacion_newStep2:
    path:       /evaluacion/new2
    defaults:   { _controller: ichTestBundle:Evaluacion:newStep2 }
    methods: POST
        
# Autenticacion

ich_test_homepage:
    path:       /
    defaults:   { _controller: ichTestBundle:Usuario:home }

ich_test_prelogin:
    path:       /prelogin
    defaults:   { _controller: ichTestBundle:Seguridad:prelogin }
    
ich_test_login:
    path:       /login
    defaults:   { _controller: ichTestBundle:Seguridad:login }

ich_test_ingresocandidato:
    path:       /ingresocandidato
    defaults:   { _controller: ichTestBundle:Seguridad:ingresocandidato }

ich_test_login_check:
    path:       /login_check
    defaults:   { _controller: ichTestBundle:Seguridad:login_check }

ich_test_logout:
    path:       /logout
