#ich_test_homepage:
#    path:     /
#    defaults: { _controller: ichTestBundle:Default:index }

# Puesto

ich_puesto_index:
    path:       /puesto/index
    defaults:   { _controller: ichTestBundle:Puesto:index }
    
ich_puesto_add:
    path:       /puesto/add
    defaults:   { _controller: ichTestBundle:Puesto:add }

ich_puesto_create:
    path:       /puesto/create
    defaults:   { _controller: ichTestBundle:Puesto:create }
    methods: POST
    
ich_puesto_edit:
    path:       /puesto/edit/{id}
    defaults:   { _controller: ichTestBundle:Puesto:edit }
    
ich_puesto_update:
    path:       /puesto/update/{id}
    defaults:   { _controller: ichTestBundle:Puesto:update }
    methods: [POST, PUT]

# Autenticacion

ich_test_homepage:
    path:       /
    defaults:   { _controller: ichTestBundle:Usuario:home }

ich_test_prelogin:
    path:       /prelogin
    defaults:   { _controller: ichTestBundle:Seguridad:prelogin }
    
ich_test_login:
    path:       /login
    defaults:   { _controller: ichTestBundle:Seguridad:login }

ich_test_ingresocandidato:
    path:       /ingresocandidato
    defaults:   { _controller: ichTestBundle:Seguridad:ingresocandidato }

ich_test_login_check:
    path:       /login_check
    defaults:   { _controller: ichTestBundle:Seguridad:login_check }

ich_test_logout:
    path:       /logout
